apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
        - name: backend-pod
          image: 0326bsj/backend
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /mugit/yaml/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
        - name: file-server-volume
          persistentVolumeClaim:
            claimName: file-server-pvc
