apiVersion: v1
kind: Service
metadata:
  name: file-server-service
spec:
  selector:
    app: file-server-pod
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-server-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mugit/data/file

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: file-server-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: file-server-pod
    spec:
      containers:
        - name: file-server-pod
          image: 0326bsj/file-server
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: config-volume
              mountPath: /mugit/yaml/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
        - name: file-server-volume
          persistentVolumeClaim:
            claimName: file-server-pvc
