apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: frontend-pod
          image: 0326bsj/frontend
          ports:
            - containerPort: 3000
