apiVersion: v1
kind: Service
metadata:
  name: sse-server-service
spec:
  selector:
    app: sse-server-pod
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: sse-server-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sse-server-pod
    spec:
      containers:
        - name: sse-server-pod
          image: 0326bsj/sse-server
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /mugit/yaml/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
