apiVersion: v1
kind: Service
metadata:
  name: redis-session-service
spec:
  selector:
    app: redis-session-pod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-session-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-session-pod
  template:
    metadata:
      labels:
        app: redis-session-pod
    spec:
      containers:
        - name: redis-session-pod
          image: redis:alpine3.19
          ports:
            - containerPort: 6379
