import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import "./globals.css";
import { Provider, createStore, atom } from "jotai";
import BottomPlaybar from "./components/bottomPlaybar/BottomPlaybar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mugit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const myStore = createStore();
  // const countAtom = atom(0);
  // myStore.set(countAtom, 1);
  // const unsub = myStore.sub(countAtom, () => {
  //   console.log("countAtom value is changed to", myStore.get(countAtom));
  // });
  // unsub() to unsubscribe

  return (
    <html lang="en">
      {/* <Provider store={myStore}> */}
      <Provider>
        <body className={inter.className} suppressHydrationWarning={true}>
          <Navbar />
          {children}
          <BottomPlaybar />
        </body>
      </Provider>
    </html>
  );
}
