import { unstable_setRequestLocale } from "next-intl/server";
import { Provider } from "jotai";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";
import BottomPlaybar from "../components/bottomPlaybar/BottomPlaybar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mugit",
  description: "Generated by create next app",
};

const locales = ["en", "ko"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <link rel="icon" href="/icon.png" type="image/png" sizes="any" />
      <Provider>
        <body className={inter.className} suppressHydrationWarning={true}>
          <Navbar />
          {children}
          <BottomPlaybar />
        </body>
      </Provider>
    </html>
  );
}
