import { NextIntlClientProvider, useMessages } from "next-intl";
import { unstable_setRequestLocale } from "next-intl/server";
import { Provider } from "jotai";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";
import BottomPlaybar from "../components/bottomPlaybar/BottomPlaybar";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mugit",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

const locales = ["en", "ko"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);
  const messages = useMessages();

  return (
    <html lang={locale}>
      <meta
        name="google-site-verification"
        content="TljhAbieSJ88uetRVi_IKKWhml5qOE5caPmegNTwC9M"
      />
      <link rel="icon" href="/icon.png" type="image/png" sizes="any" />
      <Provider>
        <body
          className={`${pretendard.variable} font-pretendard`}
          suppressHydrationWarning={true}
        >
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Navbar />
            {children}
            <BottomPlaybar />
          </NextIntlClientProvider>
        </body>
      </Provider>
    </html>
  );
}
